spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capstone?serverTimezone=Asia/Seoul
    username: root
    password: h219415
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ghkddlscks19@gmail.com
    password: acevvwsgsxbxjqaq
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          timeout: 5000
          auth: true
          starttls:
            enable: true
